base_url = "https://cv.tduyng.com"
title = "Duy NG - CV"
description = "Senior Backend Engineer - Node.js, TypeScript, AWS"
output_dir = "public"
minify_css = true
minify_html = true
minify_js = true

# Site configuration
[extra]
default_language = "fr"
base_path = ""
footer_copyright = "Â©2025 Duy NG"
